import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';
import ThemeProvider from '@/components/theme-provider';

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${rubik.variable} h-full antialiased`}>
      <ThemeProvider>
        <body className='min-h-full flex flex-col'>
          <Nav />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
